import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/footer";
import Repair from "@/components/Repair";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Estatein",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <NavBar /> */}
        <Repair />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
